version: '3'
services:
  docker_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # - /usr/app/node_modules   #Commenting this because we are getting permissions issue when running inside multipass
      - .:/usr/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    command: ["npm", "test", "a"]